### ISSUE TITLE
error invoking ConflistDel - "n2network-amf": conflistDel

### ISSUE THREAD

**Issue by josebeo2016** [Orange-OpenSource/towards5gs-helm#29]
Hello everyone.

I'm trying to install towards5gs-helm on my system. The specs:
**Kubernetes**
- K8s v1.23.4
- 2 node. 1 master, 1 worker
- Installed gpt5g module on worker node
- helm v3.8.0
- Multus v3.8
- Cilium CNI v1.11.0

**Network configuration**
Because the names of network interfaces on your Kubernetes nodes are different from eth0 and eth1, I changed all these parameter into the name of my network interface by modifying the `towards5gs-helm/charts/free5gc/values.yaml`:
```  
#Global network parametes
  n2network:
    name: n2network
    masterIf: enp0s31f6
    subnetIP: 10.100.50.248
    cidr: 29
    gatewayIP: 10.100.50.254
    excludeIP: 10.100.50.254
  n3network:
    name: n3network
    masterIf: enp0s31f6
    subnetIP: 10.100.50.232
    cidr: 29
    gatewayIP: 10.100.50.238
    excludeIP: 10.100.50.238
  n4network:
    name: n4network
    masterIf: enp0s31f6
    subnetIP: 10.100.50.240
    cidr: 29
    gatewayIP: 10.100.50.246
    excludeIP: 10.100.50.246
  n6network:
    name: n6network
    masterIf: enp0s31f6
    subnetIP: <my IP address>
    cidr: 24
    gatewayIP: <my IP gateway>
    excludeIP: 10.100.100.254
  n9network:
    name: n9network
    masterIf: enp0s31f6
    subnetIP: 10.100.50.224
    cidr: 29
    gatewayIP: 10.100.50.230
    excludeIP: 10.100.50.230
```
I also tried to change other similar config of the amf, smf and upf chart. But the problem still happens.

**The error**
`kubectl get pods -n free5gc`

```
NAME                                              READY   STATUS              RESTARTS   AGE
free5gc-v1-free5gc-amf-amf-89966854-xq5r4         0/1     Init:0/1            0          2m6s
free5gc-v1-free5gc-amf-amf-bc46d5dfc-6qpf4        0/1     Init:0/1            0          2m7s
free5gc-v1-free5gc-ausf-ausf-7c568887cd-249vf     1/1     Running             0          2m6s
free5gc-v1-free5gc-nrf-nrf-bb98d64f8-88vrm        1/1     Running             0          2m7s
free5gc-v1-free5gc-nssf-nssf-87f467897-bnprz      1/1     Running             0          2m7s
free5gc-v1-free5gc-pcf-pcf-7b66cd6494-cmt4z       1/1     Running             0          2m5s
free5gc-v1-free5gc-smf-smf-7489648d4d-h6jds       0/1     Init:0/1            0          2m3s
free5gc-v1-free5gc-smf-smf-76df75cfcf-gljvc       0/1     Init:0/1            0          2m7s
free5gc-v1-free5gc-udm-udm-757d5b546c-xj825       1/1     Running             0          2m5s
free5gc-v1-free5gc-udr-udr-7c7cc97f68-xdmmp       1/1     Running             0          2m4s
free5gc-v1-free5gc-upf-upf-658c9d59-r6r9h         0/1     ContainerCreating   0          2m7s
free5gc-v1-free5gc-upf-upf-666b689578-jtvm7       0/1     ContainerCreating   0          2m4s
free5gc-v1-free5gc-webui-webui-7d9f769968-dfqkc   1/1     Running             0          2m6s
mongodb-0                                         1/1     Running             0          2m7s

```

`kubectl describe pod -n free5gc free5gc-v1-free5gc-amf-amf-89966854-xq5r4`

```
Events:
  Type     Reason                  Age                  From               Message
  ----     ------                  ----                 ----               -------
  Normal   Scheduled               55m                  default-scheduler  Successfully assigned free5gc/free5gc-v1-free5gc-amf-amf-89966854-xq5r4 to mec-1
  Normal   AddedInterface          55m                  multus             Add eth0 [10.0.1.83/32] from cilium
  Warning  FailedCreatePodSandBox  55m                  kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "65dd9a802b8b4dc491c4a73d6870ba6532dd20355317ec4bc517b341c9a3d559" network for pod "free5gc-v1-free5gc-amf-amf-89966854-xq5r4": networkPlugin cni failed to set up pod "free5gc-v1-free5gc-amf-amf-89966854-xq5r4_free5gc" network: [free5gc/free5gc-v1-free5gc-amf-amf-89966854-xq5r4/:n2network-amf]: error adding container to network "n2network-amf": Link not found, failed to clean up sandbox container "65dd9a802b8b4dc491c4a73d6870ba6532dd20355317ec4bc517b341c9a3d559" network for pod "free5gc-v1-free5gc-amf-amf-89966854-xq5r4": networkPlugin cni failed to teardown pod "free5gc-v1-free5gc-amf-amf-89966854-xq5r4_free5gc" network: delegateDel: error invoking ConflistDel - "n2network-amf": conflistDel: error in getting result from DelNetworkList: Link not found]

```
