### ISSUE TITLE
N6 network configuration problem

### ISSUE THREAD

**Issue by seineo** [Orange-OpenSource/towards5gs-helm#60]
Hi, we're trying to deploy towards5gs-helm in Kubernetes. We made all pods running and TUN interface created, but UPF still can't reach DN via its N6 interface.
Since we have different name of network interface `enp1s0`, we followed the [Network Configuration](https://github.com/Orange-OpenSource/towards5gs-helm/tree/main/charts/free5gc#networks-configuration) to modify corresponding parameters in yaml files. We modify `masterIf` to `enp1s0`, and n6 network like this:
```
  n6network:
    name: n6network
    masterIf: enp1s0
    subnetIP: 192.168.31.0
    cidr: 24
    gatewayIP: 0.0.0.0
    excludeIP: 0.0.0.0
```
After we changed `free5gc-upf.upf.n6if.ipAddress`, the pods failed, so now it stays unchanged.

In a word, we're confused about N6 network configuration, can anyone help us?

P.S. Our node IP is 192.168.31.237/24.

Thanks.

**Comment by seineo** [comment]
After we changed the global n6network configuration as follows,
```
 n6network:
    name: n6network
    masterIf: enp1s0
    subnetIP: 192.168.31.0
    cidr: 24
    gatewayIP: 192.168.31.1
    # excludeIP: 0.0.0.0
```
and set `free5gc-upf.upf.n6if.ipAddress` as `192.168.31.89`(chose arbitrarily)， we made it work!

Note: `ip_forward`in the UPF pod should be 1.
