### ISSUE TITLE
Horizontal Pod Autoscaled (HPA)

### ISSUE THREAD

**Issue by pinoOgni** [Orange-OpenSource/towards5gs-helm#66]
Hi everybody I was trying to enable the HPA of some NFs. To do this I simply edited the "autoscaling" section in the values.yaml file i.e. switched from that
```
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
```

to this
```
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
```
But when I try to install free5gc, I get this error

```
  Error: INSTALLATION FAILED: template: free5gc/charts/free5gc-upf/templates/upf/upf-hpa.yaml:19:11: executing "free5gc/charts/free5gc-upf/templates/upf/upf-hpa.yaml" at <include "free5gc-upf.fullname" .>: error calling include: template: free5gc/charts/free5gc-upf/templates/_helpers.tpl:26:14: executing "free5gc-upf.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```

I tried to make some changes but I get other errors always related to the helpers.tpl

Does anyone know how to do?
